# Generated by Django 5.0 on 2024-01-20 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lecon',
            name='cour',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='nom',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='deleted',
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('difficulte', models.CharField(choices=[('F', 'Facile'), ('M', 'Moyenne'), ('D', 'Difficile')], max_length=1)),
                ('duree_cours', models.TimeField()),
                ('image_cours', models.ImageField(upload_to='media/images')),
                ('prix', models.FloatField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.categorie')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField()),
                ('Score', models.IntegerField(default=0)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.cours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.question')),
            ],
            options={
                'verbose_name_plural': 'Choix',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.cours')),
                ('instructeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.quiz'),
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcte', models.BooleanField(default=True)),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.choix')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.question')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.choix')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('PDF', 'fichiers pdf'), ('IMG', 'fichiers images'), ('MP4', 'fichiers video'), ('TXT', 'texte')], max_length=3)),
                ('url_ressource', models.FileField(upload_to='media/ressources')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='all.cours')),
            ],
        ),
        migrations.DeleteModel(
            name='Cour',
        ),
        migrations.DeleteModel(
            name='Lecon',
        ),
    ]
