# Generated by Django 5.0 on 2024-01-20 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_badge_question_remove_lecon_cour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
