# Generated by Django 5.0 on 2024-01-20 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_ressource_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progression',
            name='date_fin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
