# Generated by Django 5.0 on 2024-01-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0004_quiz_date_creation_alter_progression_date_fin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reponseuser',
            options={'verbose_name': 'Reponse Utilisateur', 'verbose_name_plural': 'Reponses Utilisateurs'},
        ),
    ]
